/**
 * Demo Plant LLC - FTA & Customs Module
 * Manages customs declarations and supporting document uploads
 */

import { showToast, formatFileSize } from '../utils.js?v=20260129a';
import { authenticatedFetch } from '../auth.js?v=20260428b';

let currentSubTab = 'export_other_country';
let declarations = [];
let currentDeclaration = null;

const MONTH_NAMES = ['', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'];

const TYPE_LABELS = {
    export_other_country: 'Export (Other Country)',
    export_mainland: 'Export (Mainland)',
    fta: 'FTA',
};

const STATUS_COLORS = {
    draft: 'bg-slate-100 text-slate-700',
    in_progress: 'bg-amber-100 text-amber-700',
    submitted: 'bg-blue-100 text-blue-700',
    completed: 'bg-emerald-100 text-emerald-700',
};

// Documents that can be generated by the app (export_other_country only)
const GENERATED_DOC_KINDS = {
    'Proforma Invoice': 'proforma_invoice',
    'Packing List': 'packing_list',
    'Delivery Advice': 'delivery_advice',
};

// ============================================================================
// Sub-tab switching
// ============================================================================

export function switchCustomsSubTab(tab) {
    currentSubTab = tab;
    const tabs = ['export_other_country', 'export_mainland', 'fta'];
    const activeClass = 'px-5 py-2.5 font-medium text-sm rounded-lg bg-blue-600 text-white shadow-sm border border-slate-300';
    const inactiveClass = 'px-5 py-2.5 font-medium text-sm rounded-lg bg-white text-slate-700 border border-slate-300 hover:bg-slate-50';

    tabs.forEach(t => {
        const btn = document.getElementById(`customs-subtab-${t}`);
        if (btn) btn.className = t === tab ? activeClass : inactiveClass;
    });

    const ftaPanel = document.getElementById('fta-excel-panel');
    const declPanel = document.getElementById('customs-declarations-panel');
    if (tab === 'fta') {
        if (ftaPanel) ftaPanel.classList.remove('hidden');
        if (declPanel) declPanel.classList.add('hidden');
        loadFtaTransferRefs();
    } else {
        if (ftaPanel) ftaPanel.classList.add('hidden');
        if (declPanel) declPanel.classList.remove('hidden');
    }

    closeDeclarationDetail();
    if (tab !== 'fta') loadDeclarations();
}

// ============================================================================
// Page entry
// ============================================================================

export async function loadCustomsPage() {
    const now = new Date();
    const monthSel = document.getElementById('customs-new-month');
    if (monthSel) monthSel.value = String(now.getMonth() + 1);
    const yearInp = document.getElementById('customs-new-year');
    if (yearInp) yearInp.value = String(now.getFullYear());

    const ftaMonthSel = document.getElementById('fta-month');
    if (ftaMonthSel) ftaMonthSel.value = String(now.getMonth() + 1);
    const ftaYearInp = document.getElementById('fta-year');
    if (ftaYearInp) ftaYearInp.value = String(now.getFullYear());

    switchCustomsSubTab(currentSubTab);
}

// ============================================================================
// Declarations list
// ============================================================================

async function loadDeclarations() {
    const container = document.getElementById('customs-declarations-list');
    if (!container) return;

    try {
        const res = await authenticatedFetch(`/api/customs/declarations?declaration_type=${currentSubTab}`);
        if (!res.ok) throw new Error('Failed to fetch declarations');
        const data = await res.json();
        declarations = data.declarations || [];
        renderDeclarationsList(container);
        updateStats();
    } catch (err) {
        console.error('Error loading declarations:', err);
        container.innerHTML = `<div class="p-8 text-center text-red-500">Error loading declarations</div>`;
    }
}

function updateStats() {
    const el = document.getElementById('customs-stats');
    if (!el) return;
    const total = declarations.length;
    const completed = declarations.filter(d => d.status === 'completed').length;
    el.textContent = `${total} declaration${total !== 1 ? 's' : ''} | ${completed} completed`;
}

function renderDeclarationsList(container) {
    if (!declarations.length) {
        container.innerHTML = `<div class="p-8 text-center text-slate-400">No declarations found for this category. Click "New Declaration" to create one.</div>`;
        return;
    }

    const rows = declarations.map(d => {
        const statusClass = STATUS_COLORS[d.status] || STATUS_COLORS.draft;
        const pct = d.files_required ? Math.round((d.files_uploaded / d.files_required) * 100) : 0;
        const docsLabel = d.files_required ? `${d.files_uploaded}/${d.files_required}` : `${d.files_uploaded} files`;
        return `
        <tr class="hover:bg-slate-50 cursor-pointer border-b border-slate-100" onclick="window.__viewDeclaration('${d._id}')">
            <td class="px-4 py-3 text-sm font-medium text-blue-600">${d.declaration_number}</td>
            <td class="px-4 py-3 text-sm text-slate-700">${MONTH_NAMES[d.month] || d.month} ${d.year}</td>
            <td class="px-4 py-3"><span class="inline-flex px-2.5 py-0.5 rounded-full text-xs font-medium ${statusClass}">${d.status.replace('_', ' ')}</span></td>
            <td class="px-4 py-3 text-sm text-slate-600">
                <div class="flex items-center gap-2">
                    <div class="flex-1 h-1.5 bg-slate-200 rounded-full overflow-hidden" style="max-width:80px">
                        <div class="h-full rounded-full ${pct === 100 ? 'bg-emerald-500' : 'bg-blue-500'}" style="width:${pct}%"></div>
                    </div>
                    <span>${docsLabel}</span>
                </div>
            </td>
            <td class="px-4 py-3 text-sm text-slate-500">${d.items ? d.items.length : 0} items</td>
            <td class="px-4 py-3 text-sm text-slate-500">${d.created_by || '-'}</td>
            <td class="px-4 py-3 text-right">
                <button onclick="event.stopPropagation(); window.__deleteDeclaration('${d._id}')" class="text-red-400 hover:text-red-600" title="Delete">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path></svg>
                </button>
            </td>
        </tr>`;
    }).join('');

    container.innerHTML = `
    <table class="w-full">
        <thead class="bg-slate-50">
            <tr class="text-left text-xs font-semibold text-slate-500 uppercase tracking-wider">
                <th class="px-4 py-3">Number</th>
                <th class="px-4 py-3">Period</th>
                <th class="px-4 py-3">Status</th>
                <th class="px-4 py-3">Documents</th>
                <th class="px-4 py-3">Items</th>
                <th class="px-4 py-3">Created By</th>
                <th class="px-4 py-3 text-right">Actions</th>
            </tr>
        </thead>
        <tbody>${rows}</tbody>
    </table>`;
}

// ============================================================================
// Declaration detail
// ============================================================================

async function viewDeclaration(id) {
    try {
        const res = await authenticatedFetch(`/api/customs/declarations/${id}`);
        if (!res.ok) {
            const body = await res.text().catch(() => '');
            throw new Error(`Fetch failed (${res.status}): ${body.slice(0, 200)}`);
        }
        currentDeclaration = await res.json();
    } catch (err) {
        console.error('viewDeclaration fetch error:', err);
        showToast('Error loading declaration: ' + err.message, 'error');
        return;
    }
    try {
        renderDeclarationDetail();
    } catch (err) {
        console.error('renderDeclarationDetail error:', err);
        showToast('Error rendering declaration: ' + err.message, 'error');
    }
}

function closeDeclarationDetail() {
    currentDeclaration = null;
    exportEditorState = null;
    const panel = document.getElementById('customs-detail-panel');
    if (panel) panel.classList.add('hidden');
    const editor = document.getElementById('customs-export-editor');
    if (editor) editor.classList.add('hidden');
}

function renderDeclarationDetail() {
    const panel = document.getElementById('customs-detail-panel');
    if (!panel || !currentDeclaration) return;
    panel.classList.remove('hidden');

    const d = currentDeclaration;
    document.getElementById('customs-detail-title').textContent =
        `${d.declaration_number} — ${TYPE_LABELS[d.declaration_type] || d.declaration_type}`;
    document.getElementById('customs-detail-subtitle').textContent =
        `${MONTH_NAMES[d.month] || d.month} ${d.year} | Status: ${(d.status || 'draft').replace('_', ' ')}`;

    // Documents checklist
    const docsEl = document.getElementById('customs-detail-documents');
    const requiredTypes = d.required_document_types || [];
    const uploadedFiles = d.files || [];

    if (!requiredTypes.length && !uploadedFiles.length) {
        docsEl.innerHTML = `<p class="text-slate-400 text-sm">No document types defined for this declaration type yet.</p>`;
    } else {
        const typeSet = new Set(requiredTypes);
        uploadedFiles.forEach(f => typeSet.add(f.document_type));

        const rows = Array.from(typeSet).map(docType => {
            const matchingFiles = uploadedFiles.filter(f => f.document_type === docType);
            const isRequired = requiredTypes.includes(docType);
            const uploaded = matchingFiles.length > 0;
            const generateKind = GENERATED_DOC_KINDS[docType];
            const canGenerate = !!generateKind && d.declaration_type === 'export_other_country';

            let statusBadge;
            if (uploaded) {
                statusBadge = `<span class="inline-flex items-center gap-1 text-emerald-600 text-xs font-medium"><svg class="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/></svg>${matchingFiles.some(f => f.generated) ? 'Generated' : 'Uploaded'}</span>`;
            } else if (isRequired) {
                statusBadge = `<span class="text-amber-600 text-xs font-medium">Missing</span>`;
            } else {
                statusBadge = `<span class="text-slate-400 text-xs">Optional</span>`;
            }

            const filesList = matchingFiles.map(f => {
                const fname = (f.filename || 'file').toString();
                const fnameEsc = fname.replace(/'/g, "\\'");
                return `
                <div class="flex items-center gap-2 mt-1 ml-4">
                    <a href="#" onclick="event.preventDefault(); window.__downloadFile('${f._id}', '${fnameEsc}')" class="text-sm text-blue-600 hover:underline truncate">${fname}</a>
                    <span class="text-xs text-slate-400">${formatFileSize(f.size || 0)}</span>
                    ${f.generated ? '<span class="text-[10px] text-blue-500 uppercase font-semibold">App-generated</span>' : ''}
                    <button onclick="window.__deleteFile('${f._id}')" class="text-red-400 hover:text-red-600">
                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                    </button>
                </div>`;
            }).join('');

            const openEditorBtn = canGenerate ? `
                    <button onclick="window.__openExportEditor('${generateKind}')" class="inline-flex items-center gap-1.5 px-3 py-1.5 bg-blue-600 text-white border border-blue-600 rounded-lg text-xs font-medium hover:bg-blue-700">
                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"></path></svg>
                        Open Editor
                    </button>` : '';

            return `
            <div class="flex flex-col p-3 rounded-lg border ${uploaded ? 'border-emerald-200 bg-emerald-50/30' : isRequired ? 'border-amber-200 bg-amber-50/30' : 'border-slate-200'}">
                <div class="flex items-center justify-between">
                    <div class="flex items-center gap-2">
                        <span class="text-sm font-medium text-slate-800">${docType}</span>
                        ${statusBadge}
                    </div>
                    <div class="flex items-center gap-2">
                        ${openEditorBtn}
                        ${canGenerate ? '' : `<label class="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white border border-slate-300 rounded-lg text-xs font-medium text-slate-700 hover:bg-slate-50 cursor-pointer">
                            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12"></path></svg>
                            Upload
                            <input type="file" class="hidden" onchange="window.__uploadFile(this, '${docType.replace(/'/g, "\\'")}')" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx,.xls,.xlsx">
                        </label>`}
                    </div>
                </div>
                ${filesList}
            </div>`;
        }).join('');

        docsEl.innerHTML = rows;
    }

    // Notes
    const notesEl = document.getElementById('customs-detail-notes');
    if (notesEl) notesEl.value = d.notes || '';

    panel.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ============================================================================
// Create / Delete declarations
// ============================================================================

function showNewDeclarationModal() {
    const modal = document.getElementById('customs-new-modal');
    if (modal) {
        modal.classList.remove('hidden');
        modal.classList.add('flex');
        const typeSel = document.getElementById('customs-new-type');
        if (typeSel) typeSel.value = currentSubTab;
    }
}

function closeNewDeclarationModal() {
    const modal = document.getElementById('customs-new-modal');
    if (modal) {
        modal.classList.add('hidden');
        modal.classList.remove('flex');
    }
}

async function createDeclaration() {
    const type = document.getElementById('customs-new-type')?.value;
    const month = parseInt(document.getElementById('customs-new-month')?.value, 10);
    const year = parseInt(document.getElementById('customs-new-year')?.value, 10);
    const notes = document.getElementById('customs-new-notes')?.value || '';

    if (!type || !month || !year) {
        showToast('Please fill all fields', 'error');
        return;
    }

    try {
        const res = await authenticatedFetch('/api/customs/declarations', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ declaration_type: type, month, year, notes }),
        });
        if (!res.ok) throw new Error('Failed to create');
        showToast('Declaration created', 'success');
        closeNewDeclarationModal();
        document.getElementById('customs-new-notes').value = '';
        currentSubTab = type;
        switchCustomsSubTab(type);
    } catch (err) {
        console.error(err);
        showToast('Error creating declaration', 'error');
    }
}

async function deleteDeclaration(id) {
    if (!confirm('Delete this declaration and all its files?')) return;
    try {
        const res = await authenticatedFetch(`/api/customs/declarations/${id}`, { method: 'DELETE' });
        if (!res.ok) throw new Error('Failed to delete');
        showToast('Declaration deleted', 'success');
        closeDeclarationDetail();
        loadDeclarations();
    } catch (err) {
        console.error(err);
        showToast('Error deleting declaration', 'error');
    }
}

// ============================================================================
// File upload / download / delete
// ============================================================================

async function uploadFile(inputEl, documentType) {
    if (!inputEl.files.length || !currentDeclaration) return;
    const file = inputEl.files[0];
    const formData = new FormData();
    formData.append('file', file);
    formData.append('document_type', documentType);

    try {
        const token = localStorage.getItem('demoplant_auth_token');
        const res = await fetch(`/api/customs/declarations/${currentDeclaration._id}/files`, {
            method: 'POST',
            headers: { 'Authorization': `Bearer ${token}` },
            body: formData,
        });
        if (!res.ok) throw new Error('Upload failed');
        showToast(`Uploaded ${file.name}`, 'success');
        await viewDeclaration(currentDeclaration._id);
        await loadDeclarations();
    } catch (err) {
        console.error(err);
        showToast('Error uploading file', 'error');
    }
    inputEl.value = '';
}

async function downloadFile(fileId, filename) {
    try {
        const res = await authenticatedFetch(`/api/customs/files/${fileId}`);
        if (!res.ok) throw new Error('Download failed');
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        URL.revokeObjectURL(url);
        a.remove();
    } catch (err) {
        console.error(err);
        showToast('Error downloading file', 'error');
    }
}

async function deleteFile(fileId) {
    if (!confirm('Delete this file?')) return;
    try {
        const res = await authenticatedFetch(`/api/customs/files/${fileId}`, { method: 'DELETE' });
        if (!res.ok) throw new Error('Delete failed');
        showToast('File deleted', 'success');
        if (currentDeclaration) await viewDeclaration(currentDeclaration._id);
        await loadDeclarations();
    } catch (err) {
        console.error(err);
        showToast('Error deleting file', 'error');
    }
}

// ============================================================================
// Items management (TS references)
// ============================================================================

async function showAddItemsModal() {
    if (!currentDeclaration) return;
    const modal = document.getElementById('customs-items-modal');
    if (modal) {
        modal.classList.remove('hidden');
        modal.classList.add('flex');
    }

    const listEl = document.getElementById('customs-ts-items-list');
    if (listEl) listEl.innerHTML = '<div class="text-center text-slate-400 py-4">Loading TS items...</div>';

    try {
        const res = await authenticatedFetch(
            `/api/customs/ts-items?month=${currentDeclaration.month}&year=${currentDeclaration.year}`
        );
        if (!res.ok) throw new Error('Failed');
        const data = await res.json();
        const items = data.items || [];

        const existingRefs = new Set((currentDeclaration.items || []).map(i => i.ts_reference));

        if (!items.length) {
            listEl.innerHTML = '<div class="text-center text-slate-400 py-4">No TS items found for this period.</div>';
            return;
        }

        listEl.innerHTML = items.map((item, idx) => {
            const already = existingRefs.has(item.ts_reference);
            return `
            <label class="flex items-center gap-3 p-3 rounded-lg border border-slate-200 hover:bg-slate-50 ${already ? 'opacity-50' : ''}">
                <input type="checkbox" class="customs-ts-checkbox rounded border-slate-300" data-idx="${idx}" ${already ? 'disabled checked' : ''}>
                <div class="flex-1 min-w-0">
                    <span class="font-medium text-blue-600">${item.ts_reference}</span>
                    <span class="text-slate-500 mx-2">|</span>
                    <span class="text-sm text-slate-700">${item.item_code}</span>
                    <span class="text-slate-400 mx-1">-</span>
                    <span class="text-sm text-slate-600 truncate">${item.description || ''}</span>
                </div>
                <span class="text-sm font-medium text-slate-700">${item.quantity}</span>
            </label>`;
        }).join('');

        window.__tsItemsCache = items;
    } catch (err) {
        console.error(err);
        listEl.innerHTML = '<div class="text-center text-red-500 py-4">Error loading TS items.</div>';
    }
}

function closeAddItemsModal() {
    const modal = document.getElementById('customs-items-modal');
    if (modal) {
        modal.classList.add('hidden');
        modal.classList.remove('flex');
    }
}

async function addSelectedItems() {
    if (!currentDeclaration || !window.__tsItemsCache) return;

    const checkboxes = document.querySelectorAll('.customs-ts-checkbox:checked:not(:disabled)');
    const newItems = [];
    checkboxes.forEach(cb => {
        const idx = parseInt(cb.dataset.idx, 10);
        const item = window.__tsItemsCache[idx];
        if (item) {
            newItems.push({
                item_code: item.item_code,
                description: item.description,
                quantity: item.quantity,
                batch_no: item.batch_no,
                ts_reference: item.ts_reference,
            });
        }
    });

    if (!newItems.length) {
        showToast('No items selected', 'error');
        return;
    }

    const merged = [...(currentDeclaration.items || []), ...newItems];

    try {
        const res = await authenticatedFetch(`/api/customs/declarations/${currentDeclaration._id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ items: merged }),
        });
        if (!res.ok) throw new Error('Failed');
        showToast(`Added ${newItems.length} item(s)`, 'success');
        closeAddItemsModal();
        await viewDeclaration(currentDeclaration._id);
    } catch (err) {
        console.error(err);
        showToast('Error adding items', 'error');
    }
}

async function removeItem(idx) {
    if (!currentDeclaration) return;
    const items = [...(currentDeclaration.items || [])];
    items.splice(idx, 1);

    try {
        const res = await authenticatedFetch(`/api/customs/declarations/${currentDeclaration._id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ items }),
        });
        if (!res.ok) throw new Error('Failed');
        showToast('Item removed', 'success');
        await viewDeclaration(currentDeclaration._id);
    } catch (err) {
        console.error(err);
        showToast('Error removing item', 'error');
    }
}

// ============================================================================
// Notes saving
// ============================================================================

async function saveDeclarationNotes() {
    if (!currentDeclaration) return;
    const notes = document.getElementById('customs-detail-notes')?.value || '';
    try {
        const res = await authenticatedFetch(`/api/customs/declarations/${currentDeclaration._id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ notes }),
        });
        if (!res.ok) throw new Error('Failed');
        showToast('Notes saved', 'success');
    } catch (err) {
        console.error(err);
        showToast('Error saving notes', 'error');
    }
}

// ============================================================================
// FTA Excel Automation
// ============================================================================

function getFtaPeriod() {
    const month = parseInt(document.getElementById('fta-month')?.value, 10) || new Date().getMonth() + 1;
    const year = parseInt(document.getElementById('fta-year')?.value, 10) || new Date().getFullYear();
    return { month, year };
}

async function loadFtaTransferRefs() {
    const { month, year } = getFtaPeriod();
    try {
        const res = await authenticatedFetch(`/api/customs/fta/transfers?year=${year}&month=${month}`);
        if (!res.ok) return;
        const data = await res.json();
        const refs = data.transfers || [];

        ['fta-tn-ref-203c', 'fta-tn-ref-201'].forEach(id => {
            const sel = document.getElementById(id);
            if (!sel) return;
            const current = sel.value;
            sel.innerHTML = '<option value="">All transfers (month)</option>';
            refs.forEach(r => {
                const opt = document.createElement('option');
                opt.value = r.reference;
                const dateStr = r.tx_date ? ` (${new Date(r.tx_date).toLocaleDateString()})` : '';
                opt.textContent = `${r.reference}${dateStr} - ${r.line_count} items`;
                sel.appendChild(opt);
            });
            if (current) sel.value = current;
        });
    } catch (err) {
        console.error('Error loading transfer refs:', err);
    }
}

async function downloadFtaExcel(type) {
    const { month, year } = getFtaPeriod();
    let url = `/api/customs/fta/${type}?year=${year}&month=${month}`;

    if (type === 'ex203c') {
        const ref = document.getElementById('fta-tn-ref-203c')?.value;
        if (ref) url += `&tn_ref=${encodeURIComponent(ref)}`;
    } else if (type === 'ex201') {
        const ref = document.getElementById('fta-tn-ref-201')?.value;
        if (ref) url += `&tn_ref=${encodeURIComponent(ref)}`;
    }

    try {
        showToast('Generating Excel...', 'info');
        const res = await authenticatedFetch(url);
        if (!res.ok) {
            const err = await res.text();
            throw new Error(err || 'Download failed');
        }
        const blob = await res.blob();
        const disposition = res.headers.get('Content-Disposition') || '';
        const filenameMatch = disposition.match(/filename="?([^"]+)"?/);
        const filename = filenameMatch ? filenameMatch[1] : `${type}_${year}_${month}.xlsx`;

        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        URL.revokeObjectURL(a.href);
        a.remove();
        showToast('Download complete', 'success');
    } catch (err) {
        console.error('FTA Excel download error:', err);
        showToast('Error downloading Excel: ' + err.message, 'error');
    }
}

async function loadFtaGoldenRule() {
    const { month, year } = getFtaPeriod();
    const body = document.getElementById('fta-golden-rule-body');
    const status = document.getElementById('fta-golden-status');
    if (!body) return;

    body.innerHTML = '<div class="p-8 text-center text-slate-400 text-sm">Loading...</div>';
    if (status) status.textContent = '';

    loadFtaTransferRefs();

    try {
        const res = await authenticatedFetch(`/api/customs/fta/golden-rule?year=${year}&month=${month}`);
        if (!res.ok) throw new Error('Failed to fetch golden rule');
        const data = await res.json();
        const items = data.items || [];

        if (!items.length) {
            body.innerHTML = '<div class="p-8 text-center text-slate-400 text-sm">No finished goods movements found for this period.</div>';
            return;
        }

        if (status) status.textContent = `${MONTH_NAMES[month]} ${year} | ${items.length} items`;

        const rows = items.map(item => {
            const balanced = Math.abs(
                item.opening + item.production + item.other_in
                - item.consumption - item.lost_damaged - item.transfers_out - item.other_out
                - item.closing
            ) < 0.01;
            const rowBg = balanced ? '' : 'bg-red-50';
            return `
            <tr class="${rowBg} border-b border-slate-100 hover:bg-slate-50">
                <td class="px-3 py-2 text-xs font-medium text-slate-800 whitespace-nowrap">${item.item_code}</td>
                <td class="px-3 py-2 text-xs text-slate-600 max-w-[180px] truncate" title="${item.description || ''}">${item.description || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono">${item.opening}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-emerald-600">${item.production || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-blue-600">${item.other_in || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-amber-600">${item.consumption || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-red-600">${item.lost_damaged || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-violet-600">${item.transfers_out || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono text-slate-500">${item.other_out || ''}</td>
                <td class="px-3 py-2 text-xs text-right font-mono font-bold">${item.closing}</td>
                <td class="px-3 py-2 text-center">${balanced ? '<span class="text-emerald-500">&#10003;</span>' : '<span class="text-red-500">&#10007;</span>'}</td>
            </tr>`;
        }).join('');

        body.innerHTML = `
        <table class="w-full">
            <thead class="bg-slate-50 sticky top-0">
                <tr class="text-left text-[10px] font-semibold text-slate-500 uppercase tracking-wider">
                    <th class="px-3 py-2">Item Code</th>
                    <th class="px-3 py-2">Description</th>
                    <th class="px-3 py-2 text-right">Opening</th>
                    <th class="px-3 py-2 text-right">Production</th>
                    <th class="px-3 py-2 text-right">Other In</th>
                    <th class="px-3 py-2 text-right">Consumption</th>
                    <th class="px-3 py-2 text-right">Lost/Damaged</th>
                    <th class="px-3 py-2 text-right">Transfers</th>
                    <th class="px-3 py-2 text-right">Other Out</th>
                    <th class="px-3 py-2 text-right">Closing</th>
                    <th class="px-3 py-2 text-center">OK</th>
                </tr>
            </thead>
            <tbody>${rows}</tbody>
        </table>`;

    } catch (err) {
        console.error('Golden rule error:', err);
        body.innerHTML = `<div class="p-8 text-center text-red-500 text-sm">Error loading golden rule: ${err.message}</div>`;
    }
}

async function seedProductMaster() {
    if (!confirm('Seed the FTA product master with the Demo Plant product catalog? This only adds new products (existing ones are not overwritten).')) return;
    try {
        const res = await authenticatedFetch('/api/customs/product-master/seed', { method: 'POST' });
        if (!res.ok) throw new Error('Seed failed');
        const data = await res.json();
        showToast(data.message || 'Product master seeded', 'success');
    } catch (err) {
        console.error('Seed error:', err);
        showToast('Error seeding product master: ' + err.message, 'error');
    }
}

// ============================================================================
// Export Document Editor (quotation-style page for PI / Packing List / Delivery Advice)
// ============================================================================

let exportEditorState = null;     // { docKind, draft, products }
let productCatalogCache = null;    // cached merged catalog (finished goods + price list + FTA master)

const DOC_TITLES = {
    proforma_invoice: 'Proforma Invoice',
    packing_list:     'Packing List',
    delivery_advice:  'Delivery Advice',
};

const DOC_ICONS = {
    proforma_invoice: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2',
    packing_list:     'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4',
    delivery_advice:  'M9 17a2 2 0 11-4 0 2 2 0 014 0zM19 17a2 2 0 11-4 0 2 2 0 014 0zM13 16V6a1 1 0 00-1-1H4a1 1 0 00-1 1v10a1 1 0 001 1h1m8-1a1 1 0 01-1 1H9m4-1V8a1 1 0 011-1h2.586a1 1 0 01.707.293l3.414 3.414a1 1 0 01.293.707V16a1 1 0 01-1 1h-1m-6-1a1 1 0 001 1h1M5 17a2 2 0 104 0m-4 0a2 2 0 114 0m6 0a2 2 0 104 0m-4 0a2 2 0 114 0',
};

function getNested(obj, path) {
    return path.split('.').reduce((o, k) => (o == null ? o : o[k]), obj);
}
function setNested(obj, path, value) {
    const keys = path.split('.');
    let cur = obj;
    for (let i = 0; i < keys.length - 1; i++) {
        if (cur[keys[i]] == null || typeof cur[keys[i]] !== 'object') cur[keys[i]] = {};
        cur = cur[keys[i]];
    }
    cur[keys[keys.length - 1]] = value;
}

async function fetchProductCatalog() {
    if (productCatalogCache) return productCatalogCache;
    try {
        const [fgRes, plRes, pmRes] = await Promise.all([
            authenticatedFetch('/api/finished-goods-inventory').catch(() => null),
            authenticatedFetch('/api/price-list?limit=1000').catch(() => null),
            authenticatedFetch('/api/customs/product-master').catch(() => null),
        ]);
        const fgData = fgRes && fgRes.ok ? await fgRes.json() : [];
        const plData = plRes && plRes.ok ? await plRes.json() : { items: [] };
        const pmData = pmRes && pmRes.ok ? await pmRes.json() : { products: [] };

        const priceMap = {};
        (plData.items || []).forEach(p => { priceMap[p.item_code] = p; });
        const masterMap = {};
        (pmData.products || []).forEach(p => { masterMap[p.item_code] = p; });

        const fgList = Array.isArray(fgData) ? fgData : (fgData.items || []);
        productCatalogCache = fgList.map(fg => {
            const code = fg['Item Code'] || fg.item_code || '';
            const desc = fg['Item Description'] || fg.description || '';
            const price = priceMap[code]?.base_price ?? masterMap[code]?.unit_price_aed ?? null;
            return {
                item_code: code,
                description: desc,
                unit_price_aed: price,
                hs_code: masterMap[code]?.hs_code || '',
                unit: priceMap[code]?.uom || 'Case',
            };
        }).filter(p => p.item_code);

        // Append any product-master entries not present in finished goods, so users can still pick them
        const seen = new Set(productCatalogCache.map(p => p.item_code));
        (pmData.products || []).forEach(p => {
            if (!seen.has(p.item_code)) {
                productCatalogCache.push({
                    item_code: p.item_code,
                    description: p.description || '',
                    unit_price_aed: p.unit_price_aed ?? null,
                    hs_code: p.hs_code || '',
                    unit: 'Case',
                });
            }
        });

        productCatalogCache.sort((a, b) => a.item_code.localeCompare(b.item_code));
        return productCatalogCache;
    } catch (e) {
        console.error('Error fetching product catalog', e);
        return [];
    }
}

async function openExportEditor(docKind) {
    if (!currentDeclaration) return;
    if (!DOC_TITLES[docKind]) return;

    const draft = {
        export_details: JSON.parse(JSON.stringify(currentDeclaration.export_details || {})),
        items: JSON.parse(JSON.stringify(currentDeclaration.items || [])),
    };

    // Default consignee fill on first open
    if (!draft.export_details.consignee) {
        draft.export_details.consignee = {
            name: 'DEMO PLANT (PTY) LTD',
            address_line1: 'Postnet Suite 23 Private Bag x19',
            address_line2: 'Garden View 2047',
            address_line3: 'No.2 -37th Street Malvern 2094',
            phone: '+27 11 6164617',
        };
    }
    if (!draft.export_details.delivery_method) draft.export_details.delivery_method = 'By sea';
    if (!draft.export_details.exit_point) draft.export_details.exit_point = 'Jebel Ali Freezone';
    if (!draft.export_details.country_of_origin) draft.export_details.country_of_origin = 'Jebel Ali Free Zone - UAE';
    if (!draft.export_details.country_of_origin_short) draft.export_details.country_of_origin_short = 'UAE';

    const products = await fetchProductCatalog();

    exportEditorState = { docKind, draft, products };
    renderExportEditor();
}

function closeExportEditor() {
    exportEditorState = null;
    const editor = document.getElementById('customs-export-editor');
    if (editor) editor.classList.add('hidden');
    const detail = document.getElementById('customs-detail-panel');
    if (detail) detail.classList.remove('hidden');
}

function renderExportEditor() {
    const detailPanel = document.getElementById('customs-detail-panel');
    const editor = document.getElementById('customs-export-editor');
    if (!editor || !exportEditorState) return;

    if (detailPanel) detailPanel.classList.add('hidden');
    editor.classList.remove('hidden');

    const { docKind, draft } = exportEditorState;
    const title = DOC_TITLES[docKind];
    const icon = DOC_ICONS[docKind];

    editor.innerHTML = `
    <div class="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <!-- Header -->
        <div class="px-6 py-4 border-b border-slate-200 bg-gradient-to-r from-blue-50 to-white flex items-center justify-between">
            <div class="flex items-center gap-3">
                <button onclick="window.__closeExportEditor()" class="text-slate-500 hover:text-slate-800" title="Back">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/></svg>
                </button>
                <div>
                    <h3 class="text-xl font-bold tracking-tight text-slate-900 flex items-center gap-2">
                        <svg class="w-5 h-5 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="${icon}"/></svg>
                        Build ${title}
                    </h3>
                    <p class="text-xs text-slate-500 mt-0.5">${currentDeclaration.declaration_number} • ${MONTH_NAMES[currentDeclaration.month]} ${currentDeclaration.year}</p>
                </div>
            </div>
            <div class="flex items-center gap-2">
                <button onclick="window.__saveAndGenerateExportPdf()" class="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                    Generate PDF
                </button>
            </div>
        </div>

        <!-- Body -->
        <div class="p-6">
            <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <!-- Left main column -->
                <div class="lg:col-span-2 space-y-4">
                    ${renderProductSelectCard()}
                    ${renderItemsTableCard()}
                    ${docKind === 'packing_list' ? renderContainerNumbersCard() : ''}
                    ${docKind === 'proforma_invoice' ? renderChargesCard() : ''}
                </div>

                <!-- Right sidebar -->
                <div class="space-y-4">
                    ${renderDocInfoCard()}
                    ${renderConsigneeCard()}
                    ${renderShipmentCard()}
                    ${docKind === 'delivery_advice' ? renderDeliveryAdviceCard() : ''}
                </div>
            </div>
        </div>
    </div>`;

    bindEditorInputs();
    refreshEditorItemsTable();
    refreshEditorTotals();
}

// ---- Right sidebar cards ----

function renderDocInfoCard() {
    const d = exportEditorState.draft.export_details;
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-4">
        <h4 class="font-semibold text-slate-700 mb-3 text-sm">Document Info</h4>
        <div class="space-y-3">
            <div>
                <label class="block text-xs font-medium text-slate-600 mb-1">Proforma Invoice No. *</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm focus:ring-1 focus:ring-blue-500" data-key="pi_number" placeholder="1320 EXP 2026" value="${d.pi_number || ''}">
            </div>
            <div>
                <label class="block text-xs font-medium text-slate-600 mb-1">Date</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="date" placeholder="19-Feb-26" value="${d.date || ''}">
            </div>
        </div>
    </div>`;
}

function renderConsigneeCard() {
    const c = exportEditorState.draft.export_details.consignee || {};
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-4">
        <h4 class="font-semibold text-slate-700 mb-3 text-sm">Consignee</h4>
        <div class="space-y-2">
            <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="consignee.name" placeholder="Consignee name" value="${c.name || ''}">
            <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="consignee.address_line1" placeholder="Address line 1" value="${c.address_line1 || ''}">
            <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="consignee.address_line2" placeholder="Address line 2" value="${c.address_line2 || ''}">
            <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="consignee.address_line3" placeholder="Address line 3" value="${c.address_line3 || ''}">
            <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="consignee.phone" placeholder="Phone" value="${c.phone || ''}">
        </div>
    </div>`;
}

function renderShipmentCard() {
    const d = exportEditorState.draft.export_details;
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-4">
        <h4 class="font-semibold text-slate-700 mb-3 text-sm">Shipment / Cargo</h4>
        <div class="grid grid-cols-2 gap-3">
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">H.S. Code</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="hs_code" value="${d.hs_code || ''}"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">Country of Origin</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="country_of_origin" value="${d.country_of_origin || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Place of Delivery</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="place_of_delivery" placeholder="DURBAN" value="${d.place_of_delivery || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Method</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="delivery_method" value="${d.delivery_method || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Containers Qty</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="containers_qty" value="${d.containers_qty ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Container Size</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="container_size" placeholder="40'" value="${d.container_size || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Net Weight (KG)</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="cargo_net_weight_kg" value="${d.cargo_net_weight_kg ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Gross Weight (KG)</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="cargo_gross_weight_kg" value="${d.cargo_gross_weight_kg ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Total Pallets</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="total_pallets" value="${d.total_pallets ?? ''}"></div>
        </div>
    </div>`;
}

function renderDeliveryAdviceCard() {
    const d = exportEditorState.draft.export_details;
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-4">
        <h4 class="font-semibold text-slate-700 mb-3 text-sm">Delivery Advice Codes</h4>
        <div class="grid grid-cols-2 gap-3">
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Business Code</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="business_code" placeholder="AE-1098497" value="${d.business_code || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">License No.</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="license_no" placeholder="137365" value="${d.license_no || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">DA No.</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="da_no" placeholder="1320 EXP 2026" value="${d.da_no || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Importer's Code</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="importer_code" placeholder="JC-313" value="${d.importer_code || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Agent's Code</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="agent_code" value="${d.agent_code || ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Rep Card No.</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="rep_card_no" value="${d.rep_card_no || ''}"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">Exit Point</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="exit_point" value="${d.exit_point || ''}"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">Carriers Agent</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="carriers_agent" value="${d.carriers_agent || ''}"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">Country of Origin (short)</label>
                <input type="text" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="country_of_origin_short" placeholder="UAE" value="${d.country_of_origin_short || ''}"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-slate-600 mb-1">Value AED (override)</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="value_aed" placeholder="auto from PI total" value="${d.value_aed ?? ''}"></div>
        </div>
    </div>`;
}

// ---- Left main cards ----

function renderProductSelectCard() {
    const products = exportEditorState.products || [];
    const opts = ['<option value="">-- Select Product --</option>']
        .concat(products.map(p => {
            const price = p.unit_price_aed != null ? p.unit_price_aed : '';
            return `<option value="${p.item_code}" data-price="${price}" data-hs="${p.hs_code || ''}" data-desc="${(p.description || '').replace(/"/g, '&quot;')}" data-unit="${p.unit || 'Case'}">${p.item_code} - ${p.description || ''}</option>`;
        }))
        .join('');
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-5">
        <h3 class="text-base font-bold text-slate-900 mb-3">Add Products</h3>
        <div class="grid grid-cols-1 md:grid-cols-6 gap-3 items-end">
            <div class="md:col-span-2">
                <label class="block text-xs font-medium text-slate-600 mb-1">Product</label>
                <select id="ce-product-select" class="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:ring-2 focus:ring-blue-500">${opts}</select>
            </div>
            <div>
                <label class="block text-xs font-medium text-slate-600 mb-1">Qty (Case)</label>
                <input type="number" id="ce-add-qty" value="1" min="1" class="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm">
            </div>
            <div>
                <label class="block text-xs font-medium text-slate-600 mb-1">Unit Price AED</label>
                <input type="number" id="ce-add-price" step="any" placeholder="Auto" class="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm">
            </div>
            <div>
                <label class="block text-xs font-medium text-slate-600 mb-1">Unit</label>
                <input type="text" id="ce-add-unit" value="Case" class="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm">
            </div>
            <div>
                <button onclick="window.__addEditorItem()" class="w-full px-3 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm font-medium">Add</button>
            </div>
        </div>
        <p class="text-xs text-slate-400 mt-2">Selecting a product autofills the unit price (from price list) and HS Code (if available).</p>
    </div>`;
}

function renderItemsTableCard() {
    return `
    <div class="bg-white rounded-xl border border-slate-200 overflow-hidden">
        <div class="p-4 border-b border-slate-200 bg-slate-50">
            <h3 class="font-bold text-slate-900 text-sm">Items</h3>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full">
                <thead class="bg-slate-100">
                    <tr>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-600 uppercase">Code</th>
                        <th class="px-3 py-2 text-left text-xs font-semibold text-slate-600 uppercase">Description</th>
                        <th class="px-3 py-2 text-right text-xs font-semibold text-slate-600 uppercase">Qty</th>
                        <th class="px-3 py-2 text-right text-xs font-semibold text-slate-600 uppercase">Unit Price</th>
                        <th class="px-3 py-2 text-center text-xs font-semibold text-slate-600 uppercase">Unit</th>
                        <th class="px-3 py-2 text-right text-xs font-semibold text-slate-600 uppercase">Total AED</th>
                        <th class="px-3 py-2 text-center text-xs font-semibold text-slate-600 uppercase">×</th>
                    </tr>
                </thead>
                <tbody id="ce-items-body"></tbody>
                <tfoot>
                    <tr class="bg-slate-50 border-t border-slate-200">
                        <td class="px-3 py-2 text-xs text-slate-500" colspan="2">Totals</td>
                        <td class="px-3 py-2 text-right text-xs font-bold text-slate-700" id="ce-total-qty">0</td>
                        <td colspan="2"></td>
                        <td class="px-3 py-2 text-right text-xs font-bold text-blue-600" id="ce-total-amount">AED 0.00</td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>`;
}

function renderContainerNumbersCard() {
    const containers = (exportEditorState.draft.export_details.container_numbers || []).join('\n');
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-5">
        <h3 class="text-base font-bold text-slate-900 mb-2">Container Numbers</h3>
        <p class="text-xs text-slate-500 mb-2">One container number per line. These appear in the Packing List.</p>
        <textarea id="ce-containers" rows="8" class="w-full border border-slate-300 rounded-lg px-3 py-2 text-sm font-mono focus:ring-1 focus:ring-blue-500" placeholder="MNBU0198435&#10;SUDU0075095&#10;...">${containers}</textarea>
    </div>`;
}

function renderChargesCard() {
    const c = exportEditorState.draft.export_details.charges || {};
    return `
    <div class="bg-white rounded-xl border border-slate-200 p-5">
        <h3 class="text-base font-bold text-slate-900 mb-3">Charges (AED)</h3>
        <p class="text-xs text-slate-500 mb-3">Ex work auto-fills from items total. Other charges add to CIF.</p>
        <div class="grid grid-cols-2 gap-3">
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Ex Work</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="charges.ex_work" placeholder="Auto from items" value="${c.ex_work ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Insurance</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="charges.insurance" value="${c.insurance ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Freight & Handling</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="charges.freight_and_handling" value="${c.freight_and_handling ?? ''}"></div>
            <div><label class="block text-xs font-medium text-slate-600 mb-1">Transport</label>
                <input type="number" step="any" class="ce-input w-full border border-slate-300 rounded-lg px-3 py-1.5 text-sm" data-key="charges.transport" value="${c.transport ?? ''}"></div>
        </div>
    </div>`;
}

// ---- Editor wiring ----

function bindEditorInputs() {
    // Bind right-sidebar simple inputs to draft.export_details
    document.querySelectorAll('#customs-export-editor .ce-input').forEach(inp => {
        inp.addEventListener('input', e => {
            const key = e.target.dataset.key;
            if (!key) return;
            let v = e.target.value;
            if (e.target.type === 'number') v = v === '' ? null : parseFloat(v);
            setNested(exportEditorState.draft.export_details, key, v);
            if (key.startsWith('charges.') || key === 'value_aed') refreshEditorTotals();
        });
    });

    // Container numbers
    const cont = document.getElementById('ce-containers');
    if (cont) {
        cont.addEventListener('input', e => {
            exportEditorState.draft.export_details.container_numbers =
                e.target.value.split('\n').map(s => s.trim()).filter(Boolean);
        });
    }

    // Product select autofills price + HS code + unit
    const sel = document.getElementById('ce-product-select');
    if (sel) {
        sel.addEventListener('change', e => {
            const opt = e.target.selectedOptions[0];
            if (!opt || !opt.value) return;
            const price = opt.dataset.price;
            const hs = opt.dataset.hs;
            const unit = opt.dataset.unit;
            const priceEl = document.getElementById('ce-add-price');
            const unitEl = document.getElementById('ce-add-unit');
            if (priceEl && price !== '' && price != null) priceEl.value = price;
            if (unitEl && unit) unitEl.value = unit;
            // autofill HS code if blank
            if (!exportEditorState.draft.export_details.hs_code && hs) {
                exportEditorState.draft.export_details.hs_code = hs;
                const hsInp = document.querySelector('#customs-export-editor [data-key="hs_code"]');
                if (hsInp) hsInp.value = hs;
            }
        });
    }
}

function addEditorItem() {
    if (!exportEditorState) return;
    const code = document.getElementById('ce-product-select')?.value;
    if (!code) {
        showToast('Pick a product first', 'error');
        return;
    }
    const product = (exportEditorState.products || []).find(p => p.item_code === code);
    const qty = parseFloat(document.getElementById('ce-add-qty').value || '0');
    if (!qty || qty <= 0) {
        showToast('Enter a quantity', 'error');
        return;
    }
    const priceRaw = document.getElementById('ce-add-price').value;
    const price = priceRaw === '' ? (product?.unit_price_aed ?? null) : parseFloat(priceRaw);
    const unit = document.getElementById('ce-add-unit').value || 'Case';

    exportEditorState.draft.items.push({
        item_code: code,
        description: product?.description || '',
        quantity: qty,
        unit,
        unit_price_aed: price,
    });

    // Reset add form
    document.getElementById('ce-product-select').value = '';
    document.getElementById('ce-add-qty').value = 1;
    document.getElementById('ce-add-price').value = '';

    refreshEditorItemsTable();
    refreshEditorTotals();
}

function removeEditorItem(idx) {
    if (!exportEditorState) return;
    exportEditorState.draft.items.splice(idx, 1);
    refreshEditorItemsTable();
    refreshEditorTotals();
}

function refreshEditorItemsTable() {
    const tbody = document.getElementById('ce-items-body');
    if (!tbody || !exportEditorState) return;
    const items = exportEditorState.draft.items || [];
    if (!items.length) {
        tbody.innerHTML = `<tr><td colspan="7" class="px-4 py-6 text-center text-slate-400 text-sm">No items yet. Add products above.</td></tr>`;
        return;
    }
    tbody.innerHTML = items.map((it, idx) => {
        const qty = Number(it.quantity || 0);
        const price = Number(it.unit_price_aed || 0);
        const total = qty * price;
        return `
        <tr class="border-t border-slate-100 hover:bg-slate-50/50">
            <td class="px-3 py-2 text-xs font-medium text-slate-700">${it.item_code || ''}</td>
            <td class="px-3 py-2 text-xs text-slate-600">${it.description || ''}</td>
            <td class="px-3 py-2 text-right">
                <input type="number" step="any" class="ce-item-qty w-20 text-right border border-slate-300 rounded px-2 py-1 text-xs" data-idx="${idx}" value="${qty}">
            </td>
            <td class="px-3 py-2 text-right">
                <input type="number" step="any" class="ce-item-price w-24 text-right border border-slate-300 rounded px-2 py-1 text-xs" data-idx="${idx}" value="${it.unit_price_aed ?? ''}">
            </td>
            <td class="px-3 py-2 text-center">
                <input type="text" class="ce-item-unit w-16 text-center border border-slate-300 rounded px-2 py-1 text-xs" data-idx="${idx}" value="${it.unit || 'Case'}">
            </td>
            <td class="px-3 py-2 text-right text-xs font-medium text-slate-800">${total.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2})}</td>
            <td class="px-3 py-2 text-center">
                <button onclick="window.__removeEditorItem(${idx})" class="text-red-400 hover:text-red-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                </button>
            </td>
        </tr>`;
    }).join('');

    // Bind per-row edits
    tbody.querySelectorAll('.ce-item-qty').forEach(inp => {
        inp.addEventListener('input', e => {
            const i = parseInt(e.target.dataset.idx, 10);
            exportEditorState.draft.items[i].quantity = parseFloat(e.target.value || '0');
            refreshEditorItemsTable();
            refreshEditorTotals();
        });
    });
    tbody.querySelectorAll('.ce-item-price').forEach(inp => {
        inp.addEventListener('input', e => {
            const i = parseInt(e.target.dataset.idx, 10);
            const v = e.target.value;
            exportEditorState.draft.items[i].unit_price_aed = v === '' ? null : parseFloat(v);
            refreshEditorItemsTable();
            refreshEditorTotals();
        });
    });
    tbody.querySelectorAll('.ce-item-unit').forEach(inp => {
        inp.addEventListener('input', e => {
            const i = parseInt(e.target.dataset.idx, 10);
            exportEditorState.draft.items[i].unit = e.target.value;
        });
    });
}

function refreshEditorTotals() {
    if (!exportEditorState) return;
    const items = exportEditorState.draft.items || [];
    const qtySum = items.reduce((s, it) => s + Number(it.quantity || 0), 0);
    const amtSum = items.reduce((s, it) => s + Number(it.quantity || 0) * Number(it.unit_price_aed || 0), 0);
    const qtyEl = document.getElementById('ce-total-qty');
    const amtEl = document.getElementById('ce-total-amount');
    if (qtyEl) qtyEl.textContent = qtySum.toLocaleString();
    if (amtEl) amtEl.textContent = 'AED ' + amtSum.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2});
}

async function saveAndGenerateExportPdf() {
    if (!exportEditorState || !currentDeclaration) return;
    const { docKind, draft } = exportEditorState;

    if (!draft.export_details.pi_number) {
        showToast('Proforma Invoice No. is required', 'error');
        return;
    }
    if (!draft.items.length) {
        showToast('Add at least one product', 'error');
        return;
    }

    // Auto-fill ex_work and value_aed from items if blank
    const itemsTotal = draft.items.reduce(
        (s, it) => s + Number(it.quantity || 0) * Number(it.unit_price_aed || 0), 0);
    if (draft.export_details.charges == null) draft.export_details.charges = {};
    if (!draft.export_details.charges.ex_work) draft.export_details.charges.ex_work = itemsTotal;
    if (!draft.export_details.value_aed) {
        const c = draft.export_details.charges;
        draft.export_details.value_aed = (Number(c.ex_work || 0) + Number(c.insurance || 0) +
            Number(c.freight_and_handling || 0) + Number(c.transport || 0));
    }

    try {
        // Save details + items first
        const putRes = await authenticatedFetch(`/api/customs/declarations/${currentDeclaration._id}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ export_details: draft.export_details, items: draft.items }),
        });
        if (!putRes.ok) throw new Error('Failed to save');

        // Generate PDF
        showToast('Generating PDF...', 'info');
        const res = await authenticatedFetch(
            `/api/customs/declarations/${currentDeclaration._id}/generate/${docKind}`,
            { method: 'POST' },
        );
        if (!res.ok) {
            let msg = 'Generation failed';
            try { msg = (await res.json()).detail || msg; } catch (_) {}
            throw new Error(msg);
        }
        const blob = await res.blob();
        const url = URL.createObjectURL(blob);
        window.open(url, '_blank');
        setTimeout(() => URL.revokeObjectURL(url), 30000);

        showToast(`${DOC_TITLES[docKind]} generated`, 'success');
        // Refresh underlying declaration data, then return to detail
        await viewDeclaration(currentDeclaration._id);
        await loadDeclarations();
        closeExportEditor();
    } catch (err) {
        console.error(err);
        showToast('Error: ' + err.message, 'error');
    }
}

// ============================================================================
// Expose to window for inline HTML handlers
// ============================================================================

window.__switchCustomsSubTab = switchCustomsSubTab;
window.__showNewDeclarationModal = showNewDeclarationModal;
window.__closeNewDeclarationModal = closeNewDeclarationModal;
window.__createDeclaration = createDeclaration;
window.__viewDeclaration = viewDeclaration;
window.__deleteDeclaration = deleteDeclaration;
window.__closeDeclarationDetail = closeDeclarationDetail;
window.__uploadFile = uploadFile;
window.__downloadFile = downloadFile;
window.__deleteFile = deleteFile;
window.__showAddItemsModal = showAddItemsModal;
window.__closeAddItemsModal = closeAddItemsModal;
window.__addSelectedItems = addSelectedItems;
window.__removeItem = removeItem;
window.__saveDeclarationNotes = saveDeclarationNotes;
window.__downloadFtaExcel = downloadFtaExcel;
window.__loadFtaGoldenRule = loadFtaGoldenRule;
window.__seedProductMaster = seedProductMaster;
window.__openExportEditor = openExportEditor;
window.__closeExportEditor = closeExportEditor;
window.__addEditorItem = addEditorItem;
window.__removeEditorItem = removeEditorItem;
window.__saveAndGenerateExportPdf = saveAndGenerateExportPdf;
